####
# Travis configuration for codeception-drupal-module.
####

language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - CODECEPTION_VERSION="2.0.*" DRUPAL_VERSION="drupal-7.20"
  - CODECEPTION_VERSION="2.0.*" DRUPAL_VERSION="drupal-7.x"
  - CODECEPTION_VERSION="2.1.*" DRUPAL_VERSION="drupal-7.x"

matrix:
  allow_failures:
    - CODECEPTION_VERSION="2.0.*" DRUPAL_VERSION="drupal-7.20"

mysql:
  database: travis_drupal
  user: root
  encoding: utf8

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -y -qq postfix
  - composer self-update
  # Set up the directory we're going to need during install.
  - sudo mkdir -p /var/www
  - sudo chown travis:travis /var/www

install:

  # Setup fake mailserver - Thanks to http://dropbucket.org/node/1761
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  # Install Drush globally.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  # Get a specific version of Codeception and then install Composer dependencies.
  - composer require codeception/codeception:${CODECEPTION_VERSION}
  - composer install
  # Download Drupal and get it up and running.
  - drush dl ${DRUPAL_VERSION} --destination=/var/www --drupal-project-rename=drupal
  - drush site-install -y --db-url=mysql://root@localhost/travis_drupal --db-su='root' --db-su-pw='' -r /var/www/drupal

before_script:
  # Move the Travis config into place.
  - mv travis.unit.suite.yml tests/unit.suite.yml
  # Prepare Codeception to run.
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - vendor/bin/coveralls

# Whitelist branches to test.
branches:
  only:
    - master
