####
# Travis configuration for codeception-drupal-module.
####

language: php

php:
  - 5.4
  - 5.5
  - 5.6

# This builds the environment.
install:
  - composer self-update
  - composer install

# Before running the main test script.
before_script:
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run

# Whitelist branches to test.
branches:
  only:
    - master