####
# Travis configuration for codeception-drupal-module.
####

language: php

php:
  - 5.4
  - 5.5
  - 5.6


env:
  - CODECEPTION_VERSION="2.0.*" DRUPAL_VERSION="drupal-7.20"
  - CODECEPTION_VERSION="2.0.*" DRUPAL_VERSION="drupal-7.x"
  - CODECEPTION_VERSION="2.1.*" DRUPAL_VERSION="drupal-7.x"

# This builds the environment.
install:
  - composer self-update
  - composer require codeception/codeception:${CODECEPTION_VERSION}
  - composer install

# Before running the main test script we want to ensure we've installed Drupal and set up Codeception.
before_script:
  - vendor/bin/drush dl ${DRUPAL_VERSION} --drupal-project-rename=testsites/drupal > /dev/null 2>&1 &
  - vendor/bin/drush qd --root=testsites/drupal --use-existing --account-name=admin --account-pass=admin --no-server -y > /dev/null 2>&1 &
  - ls -la
  - ls -la testsites
  - ls -la testsites/drupal
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - vendor/bin/coveralls

# Whitelist branches to test.
branches:
  only:
    - master
